### ISSUE TITLE
Failed to install from on-premise

### ISSUE THREAD

**Issue by n-WN** [passagemath/passagemath#196]
### Environment

- **OS**: macOS 14.7
- **Sage Version**: passagemath

### Steps To Reproduce

```shell
 ~/passagemath> source ~/sage/bin/activate                          main
(sage)  ~/passagemath> export PIP_CONSTRAINT="$(pwd)/constraints_pkgs.txt"
(sage)  ~/passagemath> export SAGE_CONF_TARGETS=build-local         main
(sage)  ~/passagemath> export SAGE_CONF_CONFIGURE_ARGS=/Users/passagemath/build_local
(sage)  ~/passagemath> python3 -m pip install -v passagemath-conf   main
Using pip 24.2 from /Users/sage/lib/python3.12/site-packages/pip (python 3.12)
ERROR: Exception:
Traceback (most recent call last):
  File "/Users/sage/lib/python3.12/site-packages/pip/_internal/cli/base_command.py", line 105, in _run_wrapper
    status = _inner_run()
             ^^^^^^^^^^^^
  File "/Users/sage/lib/python3.12/site-packages/pip/_internal/cli/base_command.py", line 96, in _inner_run
    return self.run(options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sage/lib/python3.12/site-packages/pip/_internal/cli/req_command.py", line 67, in wrapper
    return func(self, options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sage/lib/python3.12/site-packages/pip/_internal/commands/install.py", line 343, in run
    reqs = self.get_requirements(args, options, finder, session)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sage/lib/python3.12/site-packages/pip/_internal/cli/req_command.py", line 225, in get_requirements
    req_to_add = install_req_from_parsed_requirement(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sage/lib/python3.12/site-packages/pip/_internal/req/constructors.py", line 480, in install_req_from_parsed_requirement
    req = install_req_from_line(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sage/lib/python3.12/site-packages/pip/_internal/req/constructors.py", line 407, in install_req_from_line
    return InstallRequirement(
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/sage/lib/python3.12/site-packages/pip/_internal/req/req_install.py", line 127, in __init__
    self.local_file_path = self.link.file_path
                           ^^^^^^^^^^^^^^^^^^^
  File "/Users/sage/lib/python3.12/site-packages/pip/_internal/models/link.py", line 409, in file_path
    return url_to_path(self.url)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sage/lib/python3.12/site-packages/pip/_internal/utils/urls.py", line 36, in url_to_path
    raise ValueError(
ValueError: non-local file URIs are not supported on this platform: 'file://${SAGE_ROOT}/pkgs/sage-conf'
(sage)  ~/passagemath>    
```

### Config log

default

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

**Comment by mkoeppe** [comment]
Try `export SAGE_ROOT=$(pwd)`
