### ISSUE TITLE
passagemath-gfan Linux wheel build: No space left on device

### ISSUE THREAD

**Issue by mkoeppe** [passagemath/passagemath#322]
```
   adding: sage_wheels/bin/gfan_tropicalstartingcone (deflated 71%)
    adding: sage_wheels/bin/gfan_tropicaltraverse (deflated 71%)
    adding: sage_wheels/bin/gfan_tropicalweildivisor (deflated 71%)
    adding: sage_wheels/bin/gfan_version (deflated 71%)
  + auditwheel repair -w /tmp/cibuildwheel/repaired_wheel /tmp/cibuildwheel/built_wheel/passagemath_gfan-10.4.50-cp311-cp311-linux_x86_64.whl
  INFO:auditwheel.main_repair:Repairing passagemath_gfan-10.4.50-cp311-cp311-linux_x86_64.whl
  INFO:auditwheel.main_repair:Wheel is eligible for a higher priority tag. You requested manylinux2014_x86_64 but I have found this wheel is eligible for manylinux_2_5_x86_64.
  INFO:auditwheel.wheeltools:Previous filename tags: linux_x86_64
  INFO:auditwheel.wheeltools:New filename tags: manylinux_2_5_x86_64, manylinux1_x86_64, manylinux_2_17_x86_64, manylinux2014_x86_64
  INFO:auditwheel.wheeltools:Previous WHEEL info tags: cp311-cp311-linux_x86_64
  INFO:auditwheel.wheeltools:New WHEEL info tags: cp311-cp311-manylinux_2_5_x86_64, cp311-cp311-manylinux1_x86_64, cp311-cp311-manylinux_2_17_x86_64, cp311-cp311-manylinux2014_x86_64
  Traceback (most recent call last):
    File "/opt/_internal/cpython-3.12.7/lib/python3.12/zipfile/__init__.py", line 1901, in writestr
      dest.write(data)
    File "/opt/_internal/cpython-3.12.7/lib/python3.12/zipfile/__init__.py", line 1216, in write
      self._fileobj.write(data)
  OSError: [Errno 28] No space left on device
```
https://github.com/passagemath/passagemath/actions/runs/11716529919/job/32634909319#step:33:1546

**Comment by mkoeppe** [comment]
Fixed by #397
