### ISSUE TITLE
segfaults with PyPI sagemath-{ecl,maxima} wheels

### ISSUE THREAD

**Issue by mkoeppe** [passagemath/passagemath#616]
```
ore_algebra ➤ .tox/passagemath/bin/pip install --force-reinstall --no-deps ~/s/sage/sage-rebasing/worktree-clean/venv/var/lib/sage/wheels/passagemath_ecl-10.5.14-cp312-cp312-macosx_14_0_x86_64.whl
Processing /Users/mkoeppe/s/sage/sage-rebasing/worktree-clean/venv/var/lib/sage/wheels/passagemath_ecl-10.5.14-cp312-cp312-macosx_14_0_x86_64.whl
Installing collected packages: passagemath-ecl
  Attempting uninstall: passagemath-ecl
    Found existing installation: passagemath-ecl 10.5.14
    Uninstalling passagemath-ecl-10.5.14:
      Successfully uninstalled passagemath-ecl-10.5.14
Successfully installed passagemath-ecl-10.5.14

[notice] A new release of pip is available: 24.0 -> 24.3.1
[notice] To update, run: /Users/mkoeppe/s/sage/ore_algebra/.tox/passagemath/bin/python -m pip install --upgrade pip
ore_algebra ➤ PYTHONPATH=. .tox/passagemath/bin/sage -t --warn-long 5.0 --random-seed=278081920299208252163765582217763568770 --environment=_doctest_environment src/ore_algebra/ore_algebra.py     
Running doctests with ID 2024-12-29-16-56-09-494ff03e.
Running with SAGE_LOCAL='/Users/mkoeppe/.sage/sage-10.5.14-Darwin-x86_64/local' and SAGE_VENV='/Users/mkoeppe/s/sage/ore_algebra/.tox/passagemath'
Using --optional=homebrew,pip,sage
Features to be detected: 4ti2,SAGE_SRC,benzene,bliss,buckygen,cddexec_gmp,conway_polynomials,coxeter3,csdp,cvxopt,cvxopt,cvxpy,database_cremona_ellcurve,database_cremona_mini_ellcurve,database_cubic_hecke,database_ellcurves,database_graphs,database_jones_numfield,database_knotinfo,dot2tex,dvipng,eclib,ecm,fpylll,fricas,frobby,gap_package_atlasrep,gap_package_design,gap_package_grape,gap_package_guava,gap_package_hap,gap_package_polenta,gap_package_polycyclic,gap_package_qpa,gap_package_quagroup,gfan,giac,glucose,graphviz,imagemagick,info,ipython,jmol,jupymake,jupyter_sphinx,kenzo,kissat,latte_int,lrcalc_python,lrslib,macaulay2,mathics,matroid_database,mcqd,meataxe,mpmath,msolve,nauty,networkx,numpy,palp,pandoc,pdf2svg,pdftocairo,pexpect,phitigra,pillow,plantri,polytopes_db,polytopes_db_4d,pplpy,primecountpy,ptyprocess,pycosat,pycryptosat,pynormaliz,pyparsing,python_igraph,qepcad,requests,rpy2,rubiks,sage.all,sage.combinat,sage.geometry.polyhedron,sage.graphs,sage.groups,sage.libs.braiding,sage.libs.ecl,sage.libs.flint,sage.libs.gap,sage.libs.giac,sage.libs.homfly,sage.libs.linbox,sage.libs.m4ri,sage.libs.ntl,sage.libs.pari,sage.libs.singular,sage.misc.cython,sage.modular,sage.modules,sage.numerical.mip,sage.plot,sage.rings.complex_double,sage.rings.complex_interval_field,sage.rings.finite_rings,sage.rings.function_field,sage.rings.number_field,sage.rings.padics,sage.rings.polynomial.pbori,sage.rings.real_double,sage.rings.real_interval_field,sage.rings.real_mpfr,sage.sat,sage.schemes,sage.symbolic,sage_numerical_backends_coin,sagemath_doc_html,scipy,singular,sirocco,sloane_database,sphinx,symengine_py,sympow,sympy,tdlib,threejs,topcom
Doctesting 1 file.
sage -t --warn-long 5.0 --random-seed=278081920299208252163765582217763568770 --environment=_doctest_environment src/ore_algebra/ore_algebra.py
    Killed due to abort
**********************************************************************

Tests run before process (pid=66716) failed:
sage: from ore_algebra.ore_algebra import is_suitable_base_ring ## line 144 ##
sage: R = GF(1091)['x, y'].fraction_field()['z'] ## line 145 ##
sage: is_suitable_base_ring(R) ## line 146 ##
True
sage: is_suitable_base_ring(GF(9, 'a')) ## line 148 ##
False
sage: sig_on_count() # check sig_on/off pairings (virtual doctest) ## line 151 ##
0
sage: from ore_algebra.ore_algebra import Sigma_class ## line 180 ##
sage: R.<x1,x2,x3> = QQ['x1,x2,x3'] ## line 181 ##
sage: sigma = Sigma_class(R, {x1:2*x1, x2:1-x2, x3:x3+1}) ## line 182 ##
sage: sigma(x1+x2+x3) ## line 183 ##
2*x1 - x2 + x3 + 2
sage: sigma = Sigma_class(R.fraction_field(), {x1:2*x1, x2:1-x2, x3:x3+1}) ## line 185 ##
sage: sigma(x1+x2+x3) ## line 186 ##
2*x1 - x2 + x3 + 2
sage: R.<x1,x2,x3> = QQ['x1,x2,x3'] ## line 195 ##
sage: sigma = Sigma_class(R, {x1:2*x1, x2:1-x2, x3:x3+1}) ## line 196 ##
sage: sigma(x1+x2+x3, 5) ## line 197 ##
32*x1 - x2 + x3 + 6
sage: sigma.factorial(x1+x2+x3, 4).factor() ## line 199 ##
(x1 + x2 + x3) * (2*x1 - x2 + x3 + 2) * (4*x1 + x2 + x3 + 2) * (8*x1 - x2 + x3 + 4)
sage: sigma_inv = sigma.inverse() ## line 201 ##
sage: sigma_inv(x1+x2+x3) ## line 202 ##
1/2*x1 - x2 + x3
sage: sigma(x1+x2+x3, -1) ## line 204 ##
1/2*x1 - x2 + x3
sage: sigma.inverse().inverse() == sigma ## line 206 ##
True
sage: sorted(sigma.dict().items(), key=str) ## line 208 ##
[('x1', 2*x1), ('x2', -x2 + 1), ('x3', x3 + 1)]
sage: sig_on_count() # check sig_on/off pairings (virtual doctest) ## line 210 ##
0
sage: from ore_algebra import * ## line 359 ##
sage: R.<x> = QQ['x'] ## line 360 ##
sage: A.<Sx> = OreAlgebra(R.fraction_field(), "Sx") ## line 361 ##
sage: sigma = A.sigma() ## line 362 ##
sage: sigma_inverse = sigma.inverse() ## line 363 ##
sage: sigma(x) ## line 364 ##
x + 1
sage: sigma_inverse(x) ## line 366 ##
x - 1
sage: sig_on_count() # check sig_on/off pairings (virtual doctest) ## line 369 ##
0
sage: from ore_algebra.ore_algebra import * ## line 431 ##
sage: R.<x1,x2,x3> = QQ['x1,x2,x3'] ## line 432 ##
sage: sigma = Sigma_class(R, {x1:2*x1, x2:1-x2, x3:x3+1}) ## line 433 ##
sage: delta = Delta_class(R, {x1:1, x3:x3}, sigma) ## line 434 ##
sage: delta(x1+x2+x3) ## line 435 ##
x3 + 1
sage: delta(x1*x2*x3) ## line 437 ##
-2*x1*x2*x3 + 2*x1*x3 + x2*x3
sage: sorted(delta.dict().items(), key=str) ## line 439 ##
[('x1', 1), ('x3', x3)]
sage: sig_on_count() # check sig_on/off pairings (virtual doctest) ## line 442 ##
0
sage: from ore_algebra import * ## line 706 ##
sage: R.<x> = QQ['x'] ## line 708 ##
sage: K = R.fraction_field() ## line 709 ##
sage: A.<D> = OreAlgebra(K, ('D', lambda p: p, lambda p: p.derivative(x))) ## line 712 ##
sage: A ## line 713 ##
Univariate Ore algebra in D over Fraction Field of Univariate Polynomial Ring in x over Rational Field
sage: A.<S> = OreAlgebra(K, ('S', lambda p: p(x+1), lambda p: K.zero())) ## line 717 ##
sage: A ## line 718 ##
Univariate Ore algebra in S over Fraction Field of Univariate Polynomial Ring in x over Rational Field
sage: U.<x, y> = ZZ['x', 'y'] ## line 728 ##
sage: A.<D> = OreAlgebra(U, ('D', {}, {x:1, y:y})) ## line 731 ##
sage: B.<S> = OreAlgebra(U, ('S', {x:x+1, y:2*y}, {})) ## line 734 ##
sage: C.<Delta> = OreAlgebra(U, ('Delta', {x:x+1, y:2*y}, {x:1, y:y})) ## line 737 ##
sage: R.<x, y> = QQ['x', 'y'] ## line 765 ##
sage: A = OreAlgebra(R, 'Dx') # This creates an Ore algebra of differential operators ## line 766 ##
sage: A == OreAlgebra(R, ('Dx', {}, {x:1})) ## line 767 ##
True
sage: A == OreAlgebra(R, ('Dx', {}, {y:1})) # the Dx in A acts on x, not on y ## line 769 ##
False
sage: A = OreAlgebra(R, 'Sx') ## line 773 ##
sage: A == OreAlgebra(R, ('Sx', {x:x+1}, {})) ## line 774 ##
True
sage: A == OreAlgebra(R, ('Sx', {y:y+1}, {})) # the Sx in A acts on x, not on y ## line 776 ##
False
sage: OreAlgebra(R, 'Qx', q=2) ## line 778 ##
Univariate Ore algebra in Qx over Multivariate Polynomial Ring in x, y over Rational Field
sage: A = OreAlgebra(QQ['x'], 'Dx') ## line 806 ##
sage: A("Dx*x") ## line 807 ##
x*Dx
sage: A("Dx")*A("x") ## line 809 ##
x*Dx + 1
sage: R.<x> = QQ['x'] ## line 817 ##
sage: A.<Dx> = OreAlgebra(R, 'Dx') ## line 818 ##
sage: A([x^2+1, 5*x-7, 7*x+18]) ## line 819 ##
(7*x + 18)*Dx^2 + (5*x - 7)*Dx + x^2 + 1
sage: (7*x + 18)*Dx^2 + (5*x - 7)*Dx + x^2 + 1 ## line 821 ##
(7*x + 18)*Dx^2 + (5*x - 7)*Dx + x^2 + 1
sage: _^2 ## line 823 ##
(49*x^2 + 252*x + 324)*Dx^4 + (70*x^2 + 180*x)*Dx^3 + (14*x^3 + 61*x^2 + 49*x + 216)*Dx^2 + (10*x^3 + 14*x^2 + 107*x - 49)*Dx + x^4 + 12*x^2 + 37
sage: R.<x> = QQ['x'] ## line 826 ##
sage: A.<Sx> = OreAlgebra(QQ['x'], 'Sx') ## line 827 ##
sage: A([x^2+1, 5*x-7, 7*x+18]) ## line 828 ##
(7*x + 18)*Sx^2 + (5*x - 7)*Sx + x^2 + 1
sage: (7*x + 18)*Sx^2 + (5*x - 7)*Sx + x^2 + 1 ## line 830 ##
(7*x + 18)*Sx^2 + (5*x - 7)*Sx + x^2 + 1
sage: _^2 ## line 832 ##
(49*x^2 + 350*x + 576)*Sx^4 + (70*x^2 + 187*x - 121)*Sx^3 + (14*x^3 + 89*x^2 + 69*x + 122)*Sx^2 + (10*x^3 - 4*x^2 + x - 21)*Sx + x^4 + 2*x^2 + 1
sage: R.<x> = SR[] ## line 839 ##
sage: Dop.<Dx> = OreAlgebra(R, check_base_ring=False) ## line 840 ##
------------------------------------------------------------------------

**********************************************************************
----------------------------------------------------------------------
sage -t --warn-long 5.0 --random-seed=278081920299208252163765582217763568770 --environment=_doctest_environment src/ore_algebra/ore_algebra.py  # Killed due to abort
----------------------------------------------------------------------
Total time for all tests: 1.0 seconds
    cpu time: 0.0 seconds
    cumulative wall time: 0.0 seconds
Features detected for doctesting: 
ore_algebra ➤ .tox/passagemath/bin/pip install --force-reinstall --no-deps ~/s/sage/sage-rebasing/worktree-clean/venv/var/lib/sage/wheels/passagemath_maxima-10.5.14-cp312-cp312-macosx_14_0_x86_64.whl
Processing /Users/mkoeppe/s/sage/sage-rebasing/worktree-clean/venv/var/lib/sage/wheels/passagemath_maxima-10.5.14-cp312-cp312-macosx_14_0_x86_64.whl
Installing collected packages: passagemath-maxima
  Attempting uninstall: passagemath-maxima
    Found existing installation: passagemath-maxima 10.5.14
    Uninstalling passagemath-maxima-10.5.14:
      Successfully uninstalled passagemath-maxima-10.5.14
Successfully installed passagemath-maxima-10.5.14

[notice] A new release of pip is available: 24.0 -> 24.3.1
[notice] To update, run: /Users/mkoeppe/s/sage/ore_algebra/.tox/passagemath/bin/python -m pip install --upgrade pip
ore_algebra ➤ PYTHONPATH=. .tox/passagemath/bin/sage -t --warn-long 5.0 --random-seed=278081920299208252163765582217763568770 --environment=_doctest_environment src/ore_algebra/ore_algebra.py
Running doctests with ID 2024-12-29-16-56-43-54b97d9c.
Running with SAGE_LOCAL='/Users/mkoeppe/.sage/sage-10.5.14-Darwin-x86_64/local' and SAGE_VENV='/Users/mkoeppe/s/sage/ore_algebra/.tox/passagemath'
Using --optional=homebrew,pip,sage
Features to be detected: 4ti2,SAGE_SRC,benzene,bliss,buckygen,cddexec_gmp,conway_polynomials,coxeter3,csdp,cvxopt,cvxopt,cvxpy,database_cremona_ellcurve,database_cremona_mini_ellcurve,database_cubic_hecke,database_ellcurves,database_graphs,database_jones_numfield,database_knotinfo,dot2tex,dvipng,eclib,ecm,fpylll,fricas,frobby,gap_package_atlasrep,gap_package_design,gap_package_grape,gap_package_guava,gap_package_hap,gap_package_polenta,gap_package_polycyclic,gap_package_qpa,gap_package_quagroup,gfan,giac,glucose,graphviz,imagemagick,info,ipython,jmol,jupymake,jupyter_sphinx,kenzo,kissat,latte_int,lrcalc_python,lrslib,macaulay2,mathics,matroid_database,mcqd,meataxe,mpmath,msolve,nauty,networkx,numpy,palp,pandoc,pdf2svg,pdftocairo,pexpect,phitigra,pillow,plantri,polytopes_db,polytopes_db_4d,pplpy,primecountpy,ptyprocess,pycosat,pycryptosat,pynormaliz,pyparsing,python_igraph,qepcad,requests,rpy2,rubiks,sage.all,sage.combinat,sage.geometry.polyhedron,sage.graphs,sage.groups,sage.libs.braiding,sage.libs.ecl,sage.libs.flint,sage.libs.gap,sage.libs.giac,sage.libs.homfly,sage.libs.linbox,sage.libs.m4ri,sage.libs.ntl,sage.libs.pari,sage.libs.singular,sage.misc.cython,sage.modular,sage.modules,sage.numerical.mip,sage.plot,sage.rings.complex_double,sage.rings.complex_interval_field,sage.rings.finite_rings,sage.rings.function_field,sage.rings.number_field,sage.rings.padics,sage.rings.polynomial.pbori,sage.rings.real_double,sage.rings.real_interval_field,sage.rings.real_mpfr,sage.sat,sage.schemes,sage.symbolic,sage_numerical_backends_coin,sagemath_doc_html,scipy,singular,sirocco,sloane_database,sphinx,symengine_py,sympow,sympy,tdlib,threejs,topcom
Doctesting 1 file.
sage -t --warn-long 5.0 --random-seed=278081920299208252163765582217763568770 --environment=_doctest_environment src/ore_algebra/ore_algebra.py
**********************************************************************
File "src/ore_algebra/ore_algebra.py", line 840, in ore_algebra.ore_algebra.OreAlgebra
Failed example:
    Dop.<Dx> = OreAlgebra(R, check_base_ring=False)
Exception raised:
    Traceback (most recent call last):
      File "/Users/mkoeppe/s/sage/ore_algebra/.tox/passagemath/lib/python3.12/site-packages/sage/doctest/forker.py", line 718, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/Users/mkoeppe/s/sage/ore_algebra/.tox/passagemath/lib/python3.12/site-packages/sage/doctest/forker.py", line 1139, in compile_and_execute
        exec(compiled, globs)
      File "<doctest ore_algebra.ore_algebra.OreAlgebra[33]>", line 1, in <module>
        Dop = OreAlgebra(R, check_base_ring=False, names=('Dx',)); (Dx,) = Dop._first_ngens(1)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/mkoeppe/s/sage/ore_algebra/src/ore_algebra/ore_algebra.py", line 932, in OreAlgebra
        imgs = [(x, u, v) for x, u, v in imgs if u != x or v != zero]
                                                           ^^^^^^^^^
      File "sage/symbolic/expression.pyx", line 3465, in sage.symbolic.expression.Expression.__bool__
        m = self._maxima_()
      File "sage/symbolic/expression.pyx", line 1219, in sage.symbolic.expression.Expression._maxima_
        return super()._interface_(maxima)
      File "sage/structure/sage_object.pyx", line 711, in sage.structure.sage_object.SageObject._interface_
        nm = I.name()
      File "sage/misc/lazy_import.pyx", line 374, in sage.misc.lazy_import.LazyImport.__getattr__
        return getattr(self.get_object(), attr)
      File "sage/misc/lazy_import.pyx", line 224, in sage.misc.lazy_import.LazyImport.get_object
        return self._get_object()
      File "sage/misc/lazy_import.pyx", line 259, in sage.misc.lazy_import.LazyImport._get_object
        self._object = getattr(__import__(self._module, {}, {}, [self._name]), self._name)
      File "/Users/mkoeppe/s/sage/ore_algebra/.tox/passagemath/lib/python3.12/site-packages/sage/interfaces/maxima_lib.py", line 145, in <module>
        ecl_eval("(require 'maxima \"{}\")".format(MAXIMA_FAS))
      File "sage/libs/ecl.pyx", line 1337, in sage.libs.ecl.ecl_eval
        cpdef EclObject ecl_eval(str s):
      File "sage/libs/ecl.pyx", line 1359, in sage.libs.ecl.ecl_eval
        o = ecl_safe_eval(python_to_ecl(s, True))
      File "sage/libs/ecl.pyx", line 327, in sage.libs.ecl.ecl_safe_eval
        raise RuntimeError("ECL says: {}".format(message))
    RuntimeError: ECL says: Cannot open #P"/Users/mkoeppe/.sage/sage-10.5.14-Darwin-x86_64/local/lib/ecl/maxima.fas".
    C library error: No such file or directory
**********************************************************************
File "src/ore_algebra/ore_algebra.py", line 841, in ore_algebra.ore_algebra.OreAlgebra
Failed example:
    (Dx - pi*x)^2
Exception raised:
    Traceback (most recent call last):
      File "/Users/mkoeppe/s/sage/ore_algebra/.tox/passagemath/lib/python3.12/site-packages/sage/doctest/forker.py", line 718, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/Users/mkoeppe/s/sage/ore_algebra/.tox/passagemath/lib/python3.12/site-packages/sage/doctest/forker.py", line 1139, in compile_and_execute
        exec(compiled, globs)
      File "<doctest ore_algebra.ore_algebra.OreAlgebra[34]>", line 1, in <module>
        (Dx - pi*x)**Integer(2)
         ~~~^~~~~~
      File "sage/structure/element.pyx", line 1348, in sage.structure.element.Element.__sub__
        return coercion_model.bin_op(left, right, sub)
      File "sage/structure/coerce.pyx", line 1297, in sage.structure.coerce.CoercionModel.bin_op
        raise bin_op_exception(op, x, y)
    TypeError: unsupported operand parent(s) for -: 'Univariate Ore algebra in Dx over Univariate Polynomial Ring in x over Rational Field' and 'Univariate Polynomial Ring in x over Symbolic Ring'
**********************************************************************
1 item had failures:
   2 of  36 in ore_algebra.ore_algebra.OreAlgebra
    [162 tests, 2 failures, 2.93s wall]
----------------------------------------------------------------------
sage -t --warn-long 5.0 --random-seed=278081920299208252163765582217763568770 --environment=_doctest_environment src/ore_algebra/ore_algebra.py  # 2 doctests failed
----------------------------------------------------------------------
Total time for all tests: 3.0 seconds
    cpu time: 0.8 seconds
    cumulative wall time: 2.9 seconds
Features detected for doctesting: 
ore_algebra ➤ .tox/passagemath/bin/pip install --force-reinstall --no-deps ~/s/sage/sage-rebasing/worktree-clean/venv/var/lib/sage/wheels/passagemath_conf-10.5.14-py3-none-any.whl            
Processing /Users/mkoeppe/s/sage/sage-rebasing/worktree-clean/venv/var/lib/sage/wheels/passagemath_conf-10.5.14-py3-none-any.whl
Installing collected packages: passagemath-conf
  Attempting uninstall: passagemath-conf
    Found existing installation: passagemath-conf 10.5.14
    Uninstalling passagemath-conf-10.5.14:
      Successfully uninstalled passagemath-conf-10.5.14
Successfully installed passagemath-conf-10.5.14

[notice] A new release of pip is available: 24.0 -> 24.3.1
[notice] To update, run: /Users/mkoeppe/s/sage/ore_algebra/.tox/passagemath/bin/python -m pip install --upgrade pip
ore_algebra ➤ PYTHONPATH=. .tox/passagemath/bin/sage -t --warn-long 5.0 --random-seed=278081920299208252163765582217763568770 --environment=_doctest_environment src/ore_algebra/ore_algebra.py
Running doctests with ID 2024-12-29-16-57-30-71c26aa7.
Running with SAGE_LOCAL='/Users/mkoeppe/s/sage/sage-rebasing/worktree-clean/local' and SAGE_VENV='/Users/mkoeppe/s/sage/ore_algebra/.tox/passagemath'
Using --optional=benzene,e_antic,eigen,gp2c,homebrew,lidia,lrslib,mpsolve,normaliz,pip,sage,sage_spkg
Features to be detected: 4ti2,SAGE_SRC,benzene,bliss,buckygen,cddexec_gmp,conway_polynomials,coxeter3,csdp,cvxopt,cvxopt,cvxpy,database_cremona_ellcurve,database_cremona_mini_ellcurve,database_cubic_hecke,database_ellcurves,database_graphs,database_jones_numfield,database_knotinfo,dot2tex,dvipng,eclib,ecm,fpylll,fricas,frobby,gap_package_atlasrep,gap_package_design,gap_package_grape,gap_package_guava,gap_package_hap,gap_package_polenta,gap_package_polycyclic,gap_package_qpa,gap_package_quagroup,gfan,giac,glucose,graphviz,imagemagick,info,ipython,jmol,jupymake,jupyter_sphinx,kenzo,kissat,latte_int,lrcalc_python,lrslib,macaulay2,mathics,matroid_database,mcqd,meataxe,mpmath,msolve,nauty,networkx,numpy,palp,pandoc,pdf2svg,pdftocairo,pexpect,phitigra,pillow,plantri,polytopes_db,polytopes_db_4d,pplpy,primecountpy,ptyprocess,pycosat,pycryptosat,pynormaliz,pyparsing,python_igraph,qepcad,requests,rpy2,rubiks,sage.all,sage.combinat,sage.geometry.polyhedron,sage.graphs,sage.groups,sage.libs.braiding,sage.libs.ecl,sage.libs.flint,sage.libs.gap,sage.libs.giac,sage.libs.homfly,sage.libs.linbox,sage.libs.m4ri,sage.libs.ntl,sage.libs.pari,sage.libs.singular,sage.misc.cython,sage.modular,sage.modules,sage.numerical.mip,sage.plot,sage.rings.complex_double,sage.rings.complex_interval_field,sage.rings.finite_rings,sage.rings.function_field,sage.rings.number_field,sage.rings.padics,sage.rings.polynomial.pbori,sage.rings.real_double,sage.rings.real_interval_field,sage.rings.real_mpfr,sage.sat,sage.schemes,sage.symbolic,sage_numerical_backends_coin,sagemath_doc_html,scipy,singular,sirocco,sloane_database,sphinx,symengine_py,sympow,sympy,tdlib,threejs,topcom
Doctesting 1 file.
sage -t --warn-long 5.0 --random-seed=278081920299208252163765582217763568770 --environment=_doctest_environment src/ore_algebra/ore_algebra.py
    [162 tests, 2.21s wall]
----------------------------------------------------------------------
All tests passed!
----------------------------------------------------------------------
Total time for all tests: 2.3 seconds
    cpu time: 2.3 seconds
    cumulative wall time: 2.2 seconds
Features detected for doctesting: 
pytest is not installed in the venv, skip checking tests that rely on it
```

**Comment by mkoeppe** [comment]
- After #617, #622 no more segfault in testing `ore_algebra.py`
- Still segfaults in testing `ore_operator.py`. Does not go away with installing locally built sagemath-{ecl,maxima,conf}. Goes away with installing locally built sagemath-symbolics.

**Comment by mkoeppe** [comment]
- Fixed by #629
